name: scratch
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - ansible=6.6.0=py311h38be061_0
  - ansible-core=2.14.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - bcrypt=3.2.2=py311hd4cff14_1
  - boto=2.49.0=py_0
  - brotlipy=0.7.0=py311hd4cff14_1005
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.9.24=ha878542_0
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.15.1=py311h409f033_2
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - cryptography=38.0.3=py311h42a1071_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - dogpile.cache=1.1.8=pyhd8ed1ab_0
  - httplib2=0.21.0=pyhd8ed1ab_0
  - idna=3.4=pyhd8ed1ab_0
  - iso8601=1.1.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - jsonpatch=1.32=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - keystoneauth1=5.0.0=pyhd8ed1ab_0
  - ld_impl_linux-64=2.39=hc81fddc_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgomp=12.2.0=h65d4601_19
  - libnsl=2.0.0=h7f98852_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.40.0=h753d276_0
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.13=h166bdaf_4
  - markupsafe=2.1.1=py311hd4cff14_2
  - munch=2.5.0=py_0
  - ncurses=6.3=h27087fc_1
  - netifaces=0.11.0=py311hd4cff14_1
  - openssl=3.0.7=h166bdaf_0
  - openstacksdk=0.102.0=py311h38be061_1
  - os-service-types=1.7.0=pyh9f0ad1d_0
  - packaging=21.3=pyhd8ed1ab_0
  - paramiko=2.12.0=pyhd8ed1ab_0
  - pbr=5.11.0=pyhd8ed1ab_0
  - pip=22.3.1=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pynacl=1.5.0=py311hd4cff14_2
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.0=ha86cf86_0_cpython
  - python_abi=3.11=2_cp311
  - pyyaml=6.0=py311hd4cff14_5
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_1
  - requestsexceptions=1.4.0=py_0
  - resolvelib=0.5.4=pyhd8ed1ab_0
  - setuptools=65.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stevedore=4.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tzdata=2022f=h191b570_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
